services:
  - type: web
    name: darwin-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false  # Configurar manualmente en el panel de Render